server:
  port: 8762
spring:
  application:
    name: nativeconfigserver
# 指定从本地读取配置
  profiles:
    active: native
# 读取的路径为classpath下的shared目录
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared

#    bus:
#      trace:
#        enable: true
#    config:
#      server:
#        git:
#          uri: https://github.com/southwind9801/ordering_system.git #git仓库地址
#          searchPaths: config #仓库路径
#          username: root #git仓库用户名
#          password: root #git仓库密码
#      label: master #仓库的分支
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/