server:
  port: 8010
#  有空格
spring:
  application:
    name: order
  datasource:
    name: ordering_system
    url: jdbc:mysql://localhost:3306/ordering_system?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.liuwen.entity



